# This GHA workflow will:
# 1. Check Protobuf linting issues.
# 2. Enforce backward compatibility.
# 3. Publish Golang gRPC module to Artifactory.
name: protos
on:
  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/protos.yml'
      - 'protos/**'
  pull_request:
    paths:
      - '.github/workflows/protos.yml'
      - 'protos/**'

jobs:
  # Check Protobuf for linter issues, and backward compatibility issues.
  proto-check:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1.9.0
        with:
          github_token: ${{ github.token }}
      - name: Lint protobuf
        uses: bufbuild/buf-lint-action@v1
        with:
          input: protos
      - name: Detect breaking change
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/zhanjingjie/golang-protobuf-docker.git#branch=main'

  # Publish the Golang gRCP module to Artifactory (free for basic use cases).
  # Customize this job with your own Artifactory setup.
  publish-golang-proto-modules:
    if: github.event_name == 'push' # Publish the modules on PR merge.
    runs-on: [ubuntu-latest]
    needs: [proto-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'  
      - name: Setup Buf
        run: | 
          go install github.com/bufbuild/buf/cmd/buf@v1.7.0
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Generate code from Protos
        run: buf generate
      - name: Create Go module
        run: |
          cd protos/gen/go/helloworld/v1
          go mod init github.com/zhanjingjie/golang-protobuf-docker/grpc/helloworld
          go mod tidy
      - name: Install jFrog CLI and configure it
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://zhanjingjie.jfrog.io
      - name: Publish the Golang module to jFrog
        run: |
          cd protos/gen/go/helloworld/v1
          jfrog rt go-config
          jfrog gp jj-go v1.${{ github.run_number }}.0
